// Code generated by protoc-gen-go. DO NOT EDIT.
// source: igod.proto

package igodpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InterpretRequest struct {
	In                   string   `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterpretRequest) Reset()         { *m = InterpretRequest{} }
func (m *InterpretRequest) String() string { return proto.CompactTextString(m) }
func (*InterpretRequest) ProtoMessage()    {}
func (*InterpretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{0}
}

func (m *InterpretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterpretRequest.Unmarshal(m, b)
}
func (m *InterpretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterpretRequest.Marshal(b, m, deterministic)
}
func (m *InterpretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterpretRequest.Merge(m, src)
}
func (m *InterpretRequest) XXX_Size() int {
	return xxx_messageInfo_InterpretRequest.Size(m)
}
func (m *InterpretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterpretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterpretRequest proto.InternalMessageInfo

func (m *InterpretRequest) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

type InterpretResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterpretResponse) Reset()         { *m = InterpretResponse{} }
func (m *InterpretResponse) String() string { return proto.CompactTextString(m) }
func (*InterpretResponse) ProtoMessage()    {}
func (*InterpretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{1}
}

func (m *InterpretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterpretResponse.Unmarshal(m, b)
}
func (m *InterpretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterpretResponse.Marshal(b, m, deterministic)
}
func (m *InterpretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterpretResponse.Merge(m, src)
}
func (m *InterpretResponse) XXX_Size() int {
	return xxx_messageInfo_InterpretResponse.Size(m)
}
func (m *InterpretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterpretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterpretResponse proto.InternalMessageInfo

func (m *InterpretResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

type ParseRequest struct {
	In                   string   `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{2}
}

func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (m *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(m, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

type ParseResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseResponse) Reset()         { *m = ParseResponse{} }
func (m *ParseResponse) String() string { return proto.CompactTextString(m) }
func (*ParseResponse) ProtoMessage()    {}
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{3}
}

func (m *ParseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResponse.Unmarshal(m, b)
}
func (m *ParseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResponse.Marshal(b, m, deterministic)
}
func (m *ParseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResponse.Merge(m, src)
}
func (m *ParseResponse) XXX_Size() int {
	return xxx_messageInfo_ParseResponse.Size(m)
}
func (m *ParseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResponse proto.InternalMessageInfo

func (m *ParseResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

type DebugRequest struct {
	In                   string   `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugRequest) Reset()         { *m = DebugRequest{} }
func (m *DebugRequest) String() string { return proto.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()    {}
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{4}
}

func (m *DebugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRequest.Unmarshal(m, b)
}
func (m *DebugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRequest.Marshal(b, m, deterministic)
}
func (m *DebugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRequest.Merge(m, src)
}
func (m *DebugRequest) XXX_Size() int {
	return xxx_messageInfo_DebugRequest.Size(m)
}
func (m *DebugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRequest proto.InternalMessageInfo

func (m *DebugRequest) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

type DebugResponse struct {
	Out                  string   `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugResponse) Reset()         { *m = DebugResponse{} }
func (m *DebugResponse) String() string { return proto.CompactTextString(m) }
func (*DebugResponse) ProtoMessage()    {}
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39baff22529e1e90, []int{5}
}

func (m *DebugResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugResponse.Unmarshal(m, b)
}
func (m *DebugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugResponse.Marshal(b, m, deterministic)
}
func (m *DebugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugResponse.Merge(m, src)
}
func (m *DebugResponse) XXX_Size() int {
	return xxx_messageInfo_DebugResponse.Size(m)
}
func (m *DebugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebugResponse proto.InternalMessageInfo

func (m *DebugResponse) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func init() {
	proto.RegisterType((*InterpretRequest)(nil), "InterpretRequest")
	proto.RegisterType((*InterpretResponse)(nil), "InterpretResponse")
	proto.RegisterType((*ParseRequest)(nil), "ParseRequest")
	proto.RegisterType((*ParseResponse)(nil), "ParseResponse")
	proto.RegisterType((*DebugRequest)(nil), "DebugRequest")
	proto.RegisterType((*DebugResponse)(nil), "DebugResponse")
}

func init() { proto.RegisterFile("igod.proto", fileDescriptor_39baff22529e1e90) }

var fileDescriptor_39baff22529e1e90 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4c, 0xcf, 0x4f,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0x12, 0xf0, 0xcc, 0x2b, 0x49, 0x2d, 0x2a,
	0x28, 0x4a, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0xcc,
	0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0xcc, 0x53, 0x52, 0xe5, 0x12, 0x44, 0x52,
	0x53, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0, 0xc5, 0x9c, 0x5f, 0x5a, 0x02, 0x55, 0x05,
	0x62, 0x2a, 0xc9, 0x71, 0xf1, 0x04, 0x24, 0x16, 0x15, 0xa7, 0xe2, 0x32, 0x46, 0x91, 0x8b, 0x17,
	0x2a, 0x8f, 0xcf, 0x08, 0x97, 0xd4, 0xa4, 0xd2, 0x74, 0x3c, 0x46, 0x40, 0xe5, 0x71, 0x19, 0xe1,
	0x24, 0xc3, 0x25, 0x94, 0x9c, 0x9f, 0xab, 0x97, 0x94, 0x9a, 0x9a, 0x9c, 0x9a, 0x9a, 0xa5, 0x07,
	0xf2, 0x6a, 0x41, 0x52, 0x14, 0x1b, 0x84, 0x4e, 0x62, 0x03, 0xfb, 0xda, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x24, 0xd7, 0x30, 0x03, 0x01, 0x00, 0x00,
}
