// Code generated by protoc-gen-go. DO NOT EDIT.
// source: igo.proto

package igopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InterpretRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterpretRequest) Reset()         { *m = InterpretRequest{} }
func (m *InterpretRequest) String() string { return proto.CompactTextString(m) }
func (*InterpretRequest) ProtoMessage()    {}
func (*InterpretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da8332c9098a52c2, []int{0}
}

func (m *InterpretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterpretRequest.Unmarshal(m, b)
}
func (m *InterpretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterpretRequest.Marshal(b, m, deterministic)
}
func (m *InterpretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterpretRequest.Merge(m, src)
}
func (m *InterpretRequest) XXX_Size() int {
	return xxx_messageInfo_InterpretRequest.Size(m)
}
func (m *InterpretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterpretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterpretRequest proto.InternalMessageInfo

func (m *InterpretRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type InterpretResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterpretResponse) Reset()         { *m = InterpretResponse{} }
func (m *InterpretResponse) String() string { return proto.CompactTextString(m) }
func (*InterpretResponse) ProtoMessage()    {}
func (*InterpretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da8332c9098a52c2, []int{1}
}

func (m *InterpretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterpretResponse.Unmarshal(m, b)
}
func (m *InterpretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterpretResponse.Marshal(b, m, deterministic)
}
func (m *InterpretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterpretResponse.Merge(m, src)
}
func (m *InterpretResponse) XXX_Size() int {
	return xxx_messageInfo_InterpretResponse.Size(m)
}
func (m *InterpretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterpretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterpretResponse proto.InternalMessageInfo

func (m *InterpretResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	EvaluatedTo          string   `protobuf:"bytes,1,opt,name=evaluatedTo,proto3" json:"evaluatedTo,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_da8332c9098a52c2, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetEvaluatedTo() string {
	if m != nil {
		return m.EvaluatedTo
	}
	return ""
}

func (m *Result) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*InterpretRequest)(nil), "InterpretRequest")
	proto.RegisterType((*InterpretResponse)(nil), "InterpretResponse")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("igo.proto", fileDescriptor_da8332c9098a52c2) }

var fileDescriptor_da8332c9098a52c2 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4c, 0xcf, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe0, 0x12, 0xf0, 0xcc, 0x2b, 0x49, 0x2d, 0x2a, 0x28,
	0x4a, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0xcc, 0x2b,
	0x28, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x4c, 0xb8, 0x04, 0x91,
	0x54, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x73, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6,
	0x40, 0xd4, 0x72, 0x1b, 0xb1, 0xeb, 0x05, 0x81, 0xb9, 0x41, 0x50, 0x61, 0x25, 0x3b, 0x2e, 0x36,
	0x88, 0x88, 0x90, 0x02, 0x17, 0x77, 0x6a, 0x59, 0x62, 0x4e, 0x69, 0x62, 0x49, 0x6a, 0x4a, 0x48,
	0x3e, 0xd4, 0x6c, 0x64, 0x21, 0x21, 0x21, 0x2e, 0x96, 0xcc, 0xbc, 0xb4, 0x7c, 0x09, 0x26, 0xb0,
	0x14, 0x98, 0xed, 0xc4, 0x1e, 0xc5, 0x9a, 0x99, 0x9e, 0x5f, 0x90, 0x94, 0xc4, 0x06, 0x76, 0xaf,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x17, 0xe4, 0xca, 0xbc, 0x00, 0x00, 0x00,
}
